language: node_js
node_js:
- 6
- 8
- 9
before_script:
- npm install -g istanbul codecov

script:
  - istanbul cover ./node_modules/mocha/bin/_mocha test/spec --reporter lcovonly -- -R spec
  - codecov